### ISSUE TITLE
Local Time

### ISSUE THREAD

**Issue by fenen001** [gcobb321/icloud3_v3#296]
Hey Gary - Congrats on the release of icloud3 v3. Nice addition to my HA environment.

I run into the next issue. All time notes correspond to my HA local time.
However, only the time of 'Next Update' (every 5 minutes) for position update indicates a time of two hours before that.
I have tried to remove the icloudv3 integration in HA several times, but every time I reinstall the integration in HA, the "Next Update" time lags two hours behind. Even if I delete all corresponding files from icloudv3.

Any idea how I can fix this? Thanks in advance for your help!!

BR Huib

**Comment by gcobb321** [comment]
Does the Event Log show anything?
Can you post a screenshot of the Event Log and the regular tracking screen so I can see what you mean.

**Comment by fenen001** [comment]
Hi Gary, thank you fo your quick response!

***@***.***


As you can see the last update was 19:22:00 and the next update is 17:27:00. The strange thing is that there is really an update at the right time but it shows the time two hours before.

Hopefully you can do something with this information.

Regards, Huib


Van: Gary Cobb ***@***.***>
Beantwoorden - Aan: gcobb321/icloud3_v3 ***@***.***>
Datum: woensdag 24 april 2024 om 18:12
Aan: gcobb321/icloud3_v3 ***@***.***>
CC: Huib Fenenga ***@***.***>, Author ***@***.***>
Onderwerp: Re: [gcobb321/icloud3_v3] Local Time (Issue #296)


Does the Event Log show anything?
Can you post a screenshot of the Event Log and the regular tracking screen so I can see what you mean.

**Comment by fenen001** [comment]
<img width="298" alt="Scherm­afbeelding 2024-04-24 om 19 22 58" src="https://github.com/gcobb321/icloud3_v3/assets/133009187/7285d09f-5ef6-477d-9951-427ade42a9d9">

Hi Gary, thank you fo your quick response!

As you can see in the attachment the last update was 19:22:00 and the next update is 17:27:00. The strange thing is that there is really an update at the right time but it shows the time two hours before.
 
Hopefully you can do something with this information.
 
Regards, Huib

**Comment by gcobb321** [comment]
Look at the _Event Log_ this see what it’s going on and if there are any old location errors. It also shows these fields in the results of each tracking update. 

Are there any errors in the HA log files related to iCloud3?

**Comment by fenen001** [comment]
Hi, no errors in the HA log files and now it seems that also arrival time gives two hours before..

This is my event log and seems okayto me:

![image](https://github.com/gcobb321/icloud3_v3/assets/133009187/0582354c-2946-4aa5-8863-99f37f9bed74)

**Comment by fenen001** [comment]
[iCloud3 event log.docx](https://github.com/gcobb321/icloud3_v3/files/15107078/iCloud3.event.log.docx)

**Comment by fenen001** [comment]
Thanks for your help, attached you will find the icloud3-0.log

[icloud3-0.log.zip](https://github.com/gcobb321/icloud3_v3/files/15134058/icloud3-0.log.zip)

**Comment by gcobb321** [comment]
The Event Log looked fine. The Next and Last Update times went along with the tracking time. 

Go to Developer Tools > States and look at the actual state and attribute values for these items and see if they are correct there. If they are, do a browser refresh when you think they are wrong and see if the screen is just not being updated with the new values. Also make sure the entity names are correct and you are not seeing your wife's values instead of yours. The State values here are a better indication of what the entity value is in case the screen is not refreshing. You will notice that the attributes on these time entities also show the other time entity values.

**Comment by fenen001** [comment]
Thank you for your comments. I went to developer Tools > status. I see that the time is two hours behind. I did a browser refresh but still the same result. Attached a print screen of the entity in Developer Tools. It might be of your interest if you can something that I should change.

[Status iCloud entity.zip](https://github.com/gcobb321/icloud3_v3/files/15137599/Status.iCloud.entity.zip)

**Comment by fenen001** [comment]
I completed deleted the icloud configuration in HA, did a browser refresh and installed icloud again in HA. Same issue.

It looks like the zone.home time is wrong. In the configuration it seems that my local time is blank and caanot select. Could that mean something? Attached a screenshot from the icloud3 configuration input.

[Scherm­afbeelding 2024-04-27 om 11.46.09.zip](https://github.com/gcobb321/icloud3_v3/files/15137823/Scherm.afbeelding.2024-04-27.om.11.46.09.zip)

**Comment by gcobb321** [comment]
1. The Away Time in the last screenshot is correct.. That just means to NOT adjust the time displayed. It is used when yu are away from home and in another time zone to display local time.
2. The device_tracker attributes all agree and seem to be correct.
3. The screen shot with the times are displaying the sensor.xx_next_update_time, sensor.xx_last_located_time and sensor.xx_last_update_time entities. 

4. On the tracking screen, click the Last located, then click attributes. Mine looks like:
![image](https://github.com/gcobb321/icloud3_v3/assets/35449479/806d577c-9876-455e-a68b-905b49e71d99)

Are the times wrong on this screen or are they correct? The Next Update, Last Updated and last Located items all show the same values.

**Comment by fenen001** [comment]
Hi Gary,thanks agian for your support and patient. Attache you will find my Last Location Attributes and look the same as yours.
Attached you will also find a screenshot of all my sensors at 10:07 AM.
The 'last location attributes' seems to be okay but still if you look at all my sensors the 'next update' time is still 2 hours behind.

Any ideas? Thanks agian.

[Last location attributes.PNG.zip](https://github.com/gcobb321/icloud3_v3/files/15141388/Last.location.attributes.PNG.zip)

[All sensors.PNG.zip](https://github.com/gcobb321/icloud3_v3/files/15141390/All.sensors.PNG.zip)

**Comment by gcobb321** [comment]
You sent the Last Located image but didn't send a screenshot of the NextUpdate sensor & attributes. All the times (state & attributes) looked correct in the Last Located one. The data source for the Next Update state value is the same as the Next Update attribute on the Last Located entity. 

So far, it has been various screenshots taken at different times on different days. Lets do this.
1. Turn on debug logging (Configure > Format Parameters > Log Level=Debug (auto reset)
2. Restart HA to get a clean log file.
3. Run until you see the problem.
4. Take a screenshot of the device_tracker_huib_fenenga device_tracker entity attributes, the sensor.xxx_last_updated, sensor,xxx_next_update and sensor.xxx-last_located attributes. Also go to the Developer Tools > states and get screenshots of the same device_tradcker and sensor entities.
5. Zip all those screenshots and the icloud3-0.log file together and send to me.

Then everything should be taken at the same time and show the same information and maybe I'll notice something.
G

**Comment by fenen001** [comment]
Hi Gary, I did what you asked for. I restarted HA at 16:50 PM, attached you will find all my screenshots.

[Huib Fenenga device tracker.zip](https://github.com/gcobb321/icloud3_v3/files/15142540/Huib.Fenenga.device.tracker.zip)
[Last update.zip](https://github.com/gcobb321/icloud3_v3/files/15142541/Last.update.zip)
[Next update.zip](https://github.com/gcobb321/icloud3_v3/files/15142542/Next.update.zip)
[Last located.zip](https://github.com/gcobb321/icloud3_v3/files/15142543/Last.located.zip)
[Developper tools.zip](https://github.com/gcobb321/icloud3_v3/files/15142544/Developper.tools.zip)

**Comment by fenen001** [comment]
And I found something in my HA logbook, this looks as a fault.....

Attached the screenshot

[HA logboek.zip](https://github.com/gcobb321/icloud3_v3/files/15142545/HA.logboek.zip)

**Comment by gcobb321** [comment]
Sensor.zip will display some raw data in the event log for the time sensors as they are updated. Unzip it into the icloud3 directory and restart HA.
[sensor.zip](https://github.com/gcobb321/icloud3_v3/files/15142546/sensor.zip)

**Comment by gcobb321** [comment]
The problm in the HALogbook.zip file is corrected in the above sensor.zip. Install it and see if that corrects the issue.

**Comment by fenen001** [comment]
Thank you, you are right after installing the zip file it corrected the HA Logbook. But still have the same time issue.

And for what reason after installing the ip file I do not have an icloud3-o.log file anymore. Has this something to with 'Turn on debug logging (Configure > Format Parameters > Log Level=Debug (auto reset)'??

see attached for all files in iCloud 3 directory

[iCloud files in directory.zip](https://github.com/gcobb321/icloud3_v3/files/15143126/iCloud.files.in.directory.zip)

**Comment by gcobb321** [comment]
The icloud3-0.log file is not in the icloud3 directory, it is in the /config directory with the home-assistant.log file

![image](https://github.com/gcobb321/icloud3_v3/assets/35449479/14bcf014-1941-4179-a02b-59e3c85c9f1e)

**Comment by fenen001** [comment]
Oh shit you are right, attached the icloud3-0 file
[icloud3-0.log.zip](https://github.com/gcobb321/icloud3_v3/files/15143301/icloud3-0.log.zip)

**Comment by gcobb321** [comment]
I found something interesting - the Last Update time, which is 2-hrs off for you, is the only place in iCloud3 that gets the current time from an HA utility program. Your time zone is +2hrs. I think that time returned is already adjusted for the time zone and then gets adjusted a second time, creating the discrepancy. 

Unzip time_util.zip into the icloud3/helpers directory and restart ha. I hope it now returns the correct time. The old and new times are being logged so send me icloud3-0.log to see if it is different and now correct. What does not make sense if why it is correct for me.

[time_util.zip](https://github.com/gcobb321/icloud3_v3/files/15143844/time_util.zip)

**Comment by gcobb321** [comment]
Glad you found it. The effort got me to clean up and tune the time Utility code in iCloud3 and to uses another method of getting the time that does not use the HA time.  You can delete the time _util 2
