### ISSUE TITLE
⚠️ Apple Login Authentication Error (421, 503) ➤ Update to v3.3.3

### ISSUE THREAD

**Issue by gcobb321** [gcobb321/icloud3_v3#476]
It appears Apple made some type of change around 2:17am EST on Nov 11 to their servers and is now refusing all login and authentication requests. This is hanging up iCloud3 when it requests a location update or when HA/iCloud3 starts.

It affects all versions of iCloud3.

I am in the process of identifying what is going on and the changes that are need to get iCloud3 running again. It will probably take several days before I have a solution to this problem, just like it did the last time Apple made a change like this.

Gary

**Comment by Avinitlarge** [comment]
Would that cause this error?

Unknown error, Restart iCloud3, Untracked-()

The Apple Account is not logged into

**Comment by Sentinel79** [comment]
I can confirm this behaviour in myself. Thank you for your efforts, Gary.

**Comment by JermaNoiD** [comment]
Have we tried slapping Tim Cook yet? That might work.

**Comment by spdustin** [comment]
Thanks for your work, Gary. This is one of my favorite integrations!On Nov 13, 2025, at 6:35 PM, Gary Cobb ***@***.***> wrote:﻿gcobb321 left a comment (gcobb321/icloud3_v3#476)
Guys/Gals,
I have made some progress and have successfully logged into my Apple accounts.
Some of you may remember last November when Apple changed the method of logging into the account from sending the password to Apple for verification to using a Secure Remote Password where a hash code is sent instead. I think Apple did it again and has turned off the plain password verification method used by iCloud3.
iCloud v3.3 beta included code that supported SRP but there were problems where the verification kept expiring and the account had to be reauthenticated. The few users who were on the beta made sure it was disabled. I found some changes to the SRP code that was working in another application, changed iCloud3, worked through some other issues and managed to get a successful login.
I have some cleanup and other changes to complete and hope to have some v3.3 out this weekend.

**Comment by MrBunbao** [comment]
Thanks, jcobb! This is also one of my beloved integrations that controls a lot of my automations.

**Comment by gcobb321** [comment]
I made some progress today integrating changes to password verification, code cleanup, login error tracking and cause, disabling setting up devices when the Apple account fails to login, alert notifications, verification code entry retries, log file changes and messages and 3 or 4 other things.  

Things look like they are working ok but I am getting a 503 server error validating the password. This happens when logging into multiple accounts.  Sometimes both fail, sometimes one is ok and one fails, sometimes both log in ok. Retrying in 5-minutes seem to log the failing one in most of the time. It may be because I am hammering the Apple servers many times. Things seem good once logged in and I have a valid token. My two RPis will run all night and I’ll see how the look tomorrow. 

Thanks for all of the encouragement and well wishes. And for the coffees. Caffeine helps. Now it’s time for a margarita and wine..

I’ll probably post a beta tomorrow for you guys and gals to try.  

Gary

**Comment by Avinitlarge** [comment]
Thank you 🤩

**Comment by Remcovf** [comment]
Many many thanks for this works Gary! Greets from Europe!

**Comment by Avinitlarge** [comment]
The new update seems to be working great from me.

**Comment by Mosibi** [comment]
Version 3.3 fixed the login issue for me. Thanks!

**Comment by lnlyssg** [comment]
I'm stuck in a 503 loop, I only have the one Apple account added but it won't authenticate. I've tried waiting and restarting iCloud3 and verified it's the correct password in the settings but no luck so far

<img width="476" height="112" alt="Image" src="https://github.com/user-attachments/assets/30c8ea64-3dde-4dc1-9aa6-427fdab35d26" />

**Comment by LioBoul** [comment]
@Mosibi @Avinitlarge  Did you delete and recreate your account or just update it using the 6-digit code?

**Comment by Avinitlarge** [comment]
> @Mosibi @Avinitlarge  Did you delete and recreate your account or just update it using the 6-digit code?

I just entered the code and it worked.

**Comment by LioBoul** [comment]
Continued...
- I deleted my Apple account from iCloud v3.
- I reassigned my Apple account.
- I recovered my device from iCloud v3, but not my partner's, which had previously appeared in my account.
- I also assigned my partner's Apple account.
- Everything seems OK.
(as before, except I also had to log in to my partner's Apple account to see her iPhone)

**Comment by taugen123** [comment]
What do you mean with try again? 
Restart HA, delete account and then add account?

The official integration is also broken at the moment. Nevertheless it does auth over app specific passwords.

**Comment by ErikDB87** [comment]
Thanks for your elaborate answer, Gary! I'll look into the links you posted. 


> I think the Python code was actually ported from Java last year.

What do you mean with his exactly? Since openHAB is written in Java, I was thinking I needed to figure out the python code and 'translate' it into Java. If there's already a Java 'version', that would probably be helpful, of course. :)

**Comment by gcobb321** [comment]
I have released iCloud3 v3.3.2 with several bug fixes and other updates. Everything seems to be working a lot better. It should be available on HACS 


### Updates to iCloud3 v3.3.x
### Apple account Error 503/Password SRP handling
- Fixed several issues in the PasswordSRP handler dealing with verifying the password. This was creating the Server Not Available 503 error resulting in password authentication failures and login delays.
### Update Apple Account screen
- When the Apple account password is changed, it needs to also be changed on this screen, otherwise the account will not be logged into on the next iCloud3 restart. Fixed a problem verifying the new password, relogging into the account and requesting an authentication code.
- *Multiple Apple accounts* - Fixed a problem when going from this screen to the *Authenticate Apple Account Sign-in screen. The selected account was not being reselected.
### Authenticate Apple Account Sign-in screen
- *Multiple Apple accounts* - When several accounts need to be authenticated, the correct one was not being reselected after requesting new code.
- Improved handling of logging into the Apple account
- The Apple account login attempt would only be retried when the username and password was changed even though the account was not logged into. This as been fixed.
### Hardware Security Keys (YubiKey)
- Removed the security key selection fields from the *Authenticate Apple Account Sign-in* screen until I get it working.

**Comment by zimmerk** [comment]
Hi Gary,
my integration stopped working properly as well and I tried all kinds of mitigations. Meanwhile I'm on 3.3.3 now and still have problems logging in with a second account. 
I tried the following:
1. freshly installed 3.3.3
2. Setup my own account and added my wife's account afterwards --> mine works my wife's doesn't accept the password
3. reinstalled the integration from scratch
4. setup my wife's account --> ❌Apple Acct > y.z**0**er@, Login Failed, Error-503, Apple Server Refused Password Validation Request, Retry Later, AppleServerLocation-`usa`, Location Data not Refreshed
11-27 11:08:35 [apple_acct_s:0133]  Apple Acct > y.z**0**er@, Login Failed

Did you make any new discoveries meanwhile? 

Thanks
zim

**Comment by gcobb321** [comment]
No. Apple does not provide info on why they refused the login. You just have to retry after a while like the others did

**Comment by axxxxel** [comment]
Hi zim,
I had the same problems as you and tried a lot like updating, waiting, restarting, uninstalling, hoping etc.
At the end it is working for me again with 3.3.3 after I have changed my Apple account password.
You should give it a try if you have not yet.
Axel
